require:
  - rubocop-rspec
  - rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'Capfile'
    - 'vendor/bundle/**/*'

RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/*.rb'
